version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2

  service1:
    build: ./service_1
    ports:
      - "8001:8001"

  service2:
    build: ./service_2
    ports: 
      - "8002:8002"
